
<?php

include 'conecta.php';

$id = $_GET["id"];
$state = $_GET["state"];

if ($state == "C") {
	$lista = '{"result":[' . json_encode(getPerfis($conexao, $id)) . ']}';
	echo $lista;
}

function getPerfis($conexao, $id) {
	$retorno = array();

	$sql = "select * from perfil where academia={$id} and deletado = 'N' order by nome";

	$resultado = mysqli_query($conexao, $sql);

	while ($row = mysqli_fetch_assoc($resultado)) {
		array_push($retorno, array(
			'idperfil' => $row['idperfil'],
			'academia' => $row['academia'],
			'nome' => utf8_encode($row['nome']),
			'professor' => $row['professor'],
			'dashboard' => utf8_encode($row['dashboard']),
			'aluno_c' => utf8_encode($row['aluno_c']),
			'aluno_i' => utf8_encode($row['aluno_i']),
			'aluno_a' => utf8_encode($row['aluno_a']),
			'aluno_e' => utf8_encode($row['aluno_e']),
			'aluno_r' => utf8_encode($row['aluno_r']),
			'visitantes_c' => utf8_encode($row['visitantes_c']),
			'visitantes_i' => utf8_encode($row['visitantes_i']),
			'visitantes_a' => utf8_encode($row['visitantes_a']),
			'visitantes_e' => utf8_encode($row['visitantes_e']),
			'visitantes_r' => utf8_encode($row['visitantes_r']),
			'turma_c' => utf8_encode($row['turma_c']),
			'turma_i' => utf8_encode($row['turma_i']),
			'turma_a' => utf8_encode($row['turma_a']),
			'turma_e' => utf8_encode($row['turma_e']),
			'turma_r' => utf8_encode($row['turma_r']),
			'plano_c' => utf8_encode($row['plano_c']),
			'plano_i' => utf8_encode($row['plano_i']),
			'plano_a' => utf8_encode($row['plano_a']),
			'plano_e' => utf8_encode($row['plano_e']),
			'plano_r' => utf8_encode($row['plano_r']),
			'modalidade_c' => utf8_encode($row['modalidade_c']),
			'modalidade_i' => utf8_encode($row['modalidade_i']),
			'modalidade_a' => utf8_encode($row['modalidade_a']),
			'modalidade_e' => utf8_encode($row['modalidade_e']),
			'modalidade_r' => utf8_encode($row['modalidade_r']),
			'grupo_muscular_c' => utf8_encode($row['grupo_muscular_c']),
			'grupo_muscular_i' => utf8_encode($row['grupo_muscular_i']),
			'grupo_muscular_a' => utf8_encode($row['grupo_muscular_a']),
			'grupo_muscular_e' => utf8_encode($row['grupo_muscular_e']),
			'grupo_muscular_r' => utf8_encode($row['grupo_muscular_r']),
			'exercicios_c' => utf8_encode($row['exercicios_c']),
			'exercicios_i' => utf8_encode($row['exercicios_i']),
			'exercicios_a' => utf8_encode($row['exercicios_a']),
			'exercicios_e' => utf8_encode($row['exercicios_e']),
			'exercicios_r' => utf8_encode($row['exercicios_r']),
			'treino_padrao_c' => utf8_encode($row['treino_padrao_c']),
			'treino_padrao_i' => utf8_encode($row['treino_padrao_i']),
			'treino_padrao_a' => utf8_encode($row['treino_padrao_a']),
			'treino_padrao_e' => utf8_encode($row['treino_padrao_e']),
			'treino_padrao_r' => utf8_encode($row['treino_padrao_r']),
			'grupo_produto_c' => utf8_encode($row['grupo_produto_c']),
			'grupo_produto_i' => utf8_encode($row['grupo_produto_i']),
			'grupo_produto_a' => utf8_encode($row['grupo_produto_a']),
			'grupo_produto_e' => utf8_encode($row['grupo_produto_e']),
			'grupo_produto_r' => utf8_encode($row['grupo_produto_r']),
			'produto_c' => utf8_encode($row['produto_c']),
			'produto_i' => utf8_encode($row['produto_i']),
			'produto_a' => utf8_encode($row['produto_a']),
			'produto_e' => utf8_encode($row['produto_e']),
			'produto_r' => utf8_encode($row['produto_r']),
			'rel_alunos_com_app' => utf8_encode($row['rel_alunos_com_app']),
			'rel_sit_alunos' => utf8_encode($row['rel_sit_alunos']),
			'rel_matriculas' => utf8_encode($row['rel_matriculas']),
			'rel_alunos_sem_entrada' => utf8_encode($row['rel_alunos_sem_entrada']),
			'rel_mens_rec' => utf8_encode($row['rel_mens_rec']),
			'rel_contas' => utf8_encode($row['rel_contas']),
			'rel_vendas' => utf8_encode($row['rel_vendas']),
			'rel_recorrente' => utf8_encode($row['rel_recorrente']),
			'rel_ligacoes' => utf8_encode($row['rel_ligacoes']),
			'rel_comiss' => utf8_encode($row['rel_comiss']),
			'rel_estoque' => utf8_encode($row['rel_estoque']),
			'banco_c' => utf8_encode($row['banco_c']),
			'banco_i' => utf8_encode($row['banco_i']),
			'banco_a' => utf8_encode($row['banco_a']),
			'banco_e' => utf8_encode($row['banco_e']),
			'banco_r' => utf8_encode($row['banco_r']),
			'cartao_c' => utf8_encode($row['cartao_c']),
			'cartao_i' => utf8_encode($row['cartao_i']),
			'cartao_a' => utf8_encode($row['cartao_a']),
			'cartao_e' => utf8_encode($row['cartao_e']),
			'cartao_r' => utf8_encode($row['cartao_r']),
			'cartao_receber_c' => utf8_encode($row['cartao_receber_c']),
			'cartao_receber_b' => utf8_encode($row['cartao_receber_b']),
			'forma_pagamento_c' => utf8_encode($row['forma_pagamento_c']),
			'forma_pagamento_i' => utf8_encode($row['forma_pagamento_i']),
			'forma_pagamento_a' => utf8_encode($row['forma_pagamento_a']),
			'forma_pagamento_e' => utf8_encode($row['forma_pagamento_e']),
			'forma_pagamento_r' => utf8_encode($row['forma_pagamento_r']),
			'historico_c' => utf8_encode($row['historico_c']),
			'historico_i' => utf8_encode($row['historico_i']),
			'historico_a' => utf8_encode($row['historico_a']),
			'historico_e' => utf8_encode($row['historico_e']),
			'historico_r' => utf8_encode($row['historico_r']),
			'venda_c' => utf8_encode($row['venda_c']),
			'venda_i' => utf8_encode($row['venda_i']),
			'venda_canc' => utf8_encode($row['venda_canc']),
			'venda_e' => utf8_encode($row['venda_e']),
			'venda_r' => utf8_encode($row['venda_r']),
			'pagar_c' => utf8_encode($row['pagar_c']),
			'pagar_i' => utf8_encode($row['pagar_i']),
			'pagar_a' => utf8_encode($row['pagar_a']),
			'pagar_e' => utf8_encode($row['pagar_e']),
			'pagar_r' => utf8_encode($row['pagar_r']),
			'movimento_caixa_c' => utf8_encode($row['movimento_caixa_c']),
			'movimento_caixa_i' => utf8_encode($row['movimento_caixa_i']),
			'movimento_caixa_a' => utf8_encode($row['movimento_caixa_a']),
			'movimento_caixa_e' => utf8_encode($row['movimento_caixa_e']),
			'movimento_caixa_r' => utf8_encode($row['movimento_caixa_r']),
			'rec_inicio_c' => utf8_encode($row['rec_inicio_c']),
			'rec_inicio_i' => utf8_encode($row['rec_inicio_i']),
			'rec_inicio_a' => utf8_encode($row['rec_inicio_a']),
			'rec_inicio_e' => utf8_encode($row['rec_inicio_e']),
			'rec_inicio_r' => utf8_encode($row['rec_inicio_r']),
			'rec_verif_contas_c' => utf8_encode($row['rec_verif_contas_c']),
			'rec_verif_contas_i' => utf8_encode($row['rec_verif_contas_i']),
			'rec_verif_contas_a' => utf8_encode($row['rec_verif_contas_a']),
			'rec_verif_contas_e' => utf8_encode($row['rec_verif_contas_e']),
			'rec_verif_contas_r' => utf8_encode($row['rec_verif_contas_r']),
			'rec_clientes_c' => utf8_encode($row['rec_clientes_c']),
			'rec_clientes_i' => utf8_encode($row['rec_clientes_i']),
			'rec_clientes_a' => utf8_encode($row['rec_clientes_a']),
			'rec_clientes_e' => utf8_encode($row['rec_clientes_e']),
			'rec_clientes_r' => utf8_encode($row['rec_clientes_r']),
			'rec_faturas_c' => utf8_encode($row['rec_faturas_c']),
			'rec_faturas_i' => utf8_encode($row['rec_faturas_i']),
			'rec_faturas_a' => utf8_encode($row['rec_faturas_a']),
			'rec_faturas_e' => utf8_encode($row['rec_faturas_e']),
			'rec_faturas_r' => utf8_encode($row['rec_faturas_r']),
			'rec_charge_c' => utf8_encode($row['rec_charge_c']),
			'rec_charge_i' => utf8_encode($row['rec_charge_i']),
			'rec_charge_a' => utf8_encode($row['rec_charge_a']),
			'rec_charge_e' => utf8_encode($row['rec_charge_e']),
			'rec_charge_r' => utf8_encode($row['rec_charge_r']),
			'rec_assin_c' => utf8_encode($row['rec_assin_c']),
			'rec_assin_i' => utf8_encode($row['rec_assin_i']),
			'rec_assin_a' => utf8_encode($row['rec_assin_a']),
			'rec_assin_e' => utf8_encode($row['rec_assin_e']),
			'rec_assin_r' => utf8_encode($row['rec_assin_r']),
			'rec_planos_c' => utf8_encode($row['rec_planos_c']),
			'rec_planos_i' => utf8_encode($row['rec_planos_i']),
			'rec_planos_a' => utf8_encode($row['rec_planos_a']),
			'rec_planos_e' => utf8_encode($row['rec_planos_e']),
			'rec_planos_r' => utf8_encode($row['rec_planos_r']),
			'rec_subconta_c' => utf8_encode($row['rec_subconta_c']),
			'rec_subconta_i' => utf8_encode($row['rec_subconta_i']),
			'rec_subconta_a' => utf8_encode($row['rec_subconta_a']),
			'rec_subconta_e' => utf8_encode($row['rec_subconta_e']),
			'rec_subconta_r' => utf8_encode($row['rec_subconta_r']),
			'equipe_c' => utf8_encode($row['equipe_c']),
			'equipe_i' => utf8_encode($row['equipe_i']),
			'equipe_a' => utf8_encode($row['equipe_a']),
			'equipe_e' => utf8_encode($row['equipe_e']),
			'equipe_r' => utf8_encode($row['equipe_r']),
			'perfil_c' => utf8_encode($row['perfil_c']),
			'perfil_i' => utf8_encode($row['perfil_i']),
			'perfil_a' => utf8_encode($row['perfil_a']),
			'perfil_e' => utf8_encode($row['perfil_e']),
			'perfil_r' => utf8_encode($row['perfil_r']),
			'contr_entr_c' => utf8_encode($row['contr_entr_c']),
			'contr_entr_i' => utf8_encode($row['contr_entr_i']),
			'contr_entr_a' => utf8_encode($row['contr_entr_a']),
			'contr_entr_e' => utf8_encode($row['contr_entr_e']),
			'contr_entr_r' => utf8_encode($row['contr_entr_r']),
			'reg_atriv_c' => utf8_encode($row['reg_atriv_c']),
			'reg_atriv_i' => utf8_encode($row['reg_atriv_i']),
			'reg_atriv_a' => utf8_encode($row['reg_atriv_a']),
			'reg_atriv_e' => utf8_encode($row['reg_atriv_e']),
			'reg_atriv_r' => utf8_encode($row['reg_atriv_r']),




			'deletado' => utf8_encode($row['deletado'])

		));
	}

	return $retorno;
}


